# Generated by Django 3.2.4 on 2021-08-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('ASIN', models.CharField(max_length=13)),
                ('pages', models.IntegerField(verbose_name='10')),
                ('price', models.IntegerField()),
                ('book_url', models.URLField()),
                ('publisher', models.CharField(max_length=15)),
                ('publication_date', models.DateField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=150)),
                ('story_line', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('staring', models.CharField(max_length=150)),
                ('poster_image', models.URLField()),
                ('year_released', models.DateTimeField()),
            ],
        ),
    ]
