# Generated by Django 3.2.4 on 2021-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_api', '0002_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
    ]
