# Generated by Django 3.2.4 on 2021-08-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_api', '0003_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
