# Generated by Django 3.2.4 on 2021-08-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_api', '0004_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='staring',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='story_line',
            field=models.CharField(max_length=400),
        ),
    ]
